format = "$all"

[aws]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[gcloud]
disabled = true

[kubernetes]
disabled = false

[shlvl]
disabled = false
threshold = 3

[status]
disabled = false
